//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSC_Simulator.R2RReplyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Adapter/SMSC_R2R_ControllerService_Reply", ConfigurationName="R2RReplyService.SMSC_R2R_ControllerService_ReplySoap")]
    public interface SMSC_R2R_ControllerService_ReplySoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Adapter/SMSC_R2R_ControllerService_Reply/SMSC_R2R_CMP_CalcRecipeSettings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SMSC_R2R_CMP_CalcRecipeSettings(SMSC_Simulator.R2RReplyService.eventInfo SMSC_R2R_CMP_CalcRecipeSettings_input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Adapter/SMSC_R2R_ControllerService_Reply/SMSC_R2R_CMP_CalcRecipeSettings", ReplyAction="*")]
        System.Threading.Tasks.Task SMSC_R2R_CMP_CalcRecipeSettingsAsync(SMSC_Simulator.R2RReplyService.eventInfo SMSC_R2R_CMP_CalcRecipeSettings_input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Adapter/SMSC_R2R_ControllerService_Reply/SMSC_R2R_CMP_Metrology", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SMSC_R2R_CMP_Metrology(SMSC_Simulator.R2RReplyService.eventInfo1 SMSC_R2R_CMP_Metrology_input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Adapter/SMSC_R2R_ControllerService_Reply/SMSC_R2R_CMP_Metrology", ReplyAction="*")]
        System.Threading.Tasks.Task SMSC_R2R_CMP_MetrologyAsync(SMSC_Simulator.R2RReplyService.eventInfo1 SMSC_R2R_CMP_Metrology_input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Adapter/SMSC_R2R_ControllerService_Reply/SMSC_R2R_CMP_UsedSettings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SMSC_R2R_CMP_UsedSettings(SMSC_Simulator.R2RReplyService.eventInfo2 SMSC_R2R_CMP_UsedSettings_input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Adapter/SMSC_R2R_ControllerService_Reply/SMSC_R2R_CMP_UsedSettings", ReplyAction="*")]
        System.Threading.Tasks.Task SMSC_R2R_CMP_UsedSettingsAsync(SMSC_Simulator.R2RReplyService.eventInfo2 SMSC_R2R_CMP_UsedSettings_input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Adapter/SMSC_R2R_ControllerService_Reply/SMSC_R2R_CVD_CalcRecipeSettings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SMSC_R2R_CVD_CalcRecipeSettings(SMSC_Simulator.R2RReplyService.eventInfo3 SMSC_R2R_CVD_CalcRecipeSettings_input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Adapter/SMSC_R2R_ControllerService_Reply/SMSC_R2R_CVD_CalcRecipeSettings", ReplyAction="*")]
        System.Threading.Tasks.Task SMSC_R2R_CVD_CalcRecipeSettingsAsync(SMSC_Simulator.R2RReplyService.eventInfo3 SMSC_R2R_CVD_CalcRecipeSettings_input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Adapter/SMSC_R2R_ControllerService_Reply/SMSC_R2R_CVD_Metrology", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SMSC_R2R_CVD_Metrology(SMSC_Simulator.R2RReplyService.eventInfo4 SMSC_R2R_CVD_Metrology_input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Adapter/SMSC_R2R_ControllerService_Reply/SMSC_R2R_CVD_Metrology", ReplyAction="*")]
        System.Threading.Tasks.Task SMSC_R2R_CVD_MetrologyAsync(SMSC_Simulator.R2RReplyService.eventInfo4 SMSC_R2R_CVD_Metrology_input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Adapter/SMSC_R2R_ControllerService_Reply/SMSC_R2R_CVD_UsedSettings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SMSC_R2R_CVD_UsedSettings(SMSC_Simulator.R2RReplyService.eventInfo5 SMSC_R2R_CVD_UsedSettings_input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Adapter/SMSC_R2R_ControllerService_Reply/SMSC_R2R_CVD_UsedSettings", ReplyAction="*")]
        System.Threading.Tasks.Task SMSC_R2R_CVD_UsedSettingsAsync(SMSC_Simulator.R2RReplyService.eventInfo5 SMSC_R2R_CVD_UsedSettings_input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Adapter/SMSC_R2R_ControllerService_Reply/SMSC_R2R_CommonFunction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SMSC_R2R_CommonFunction(SMSC_Simulator.R2RReplyService.eventInfo6 SMSC_R2R_CommonFunction_input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Adapter/SMSC_R2R_ControllerService_Reply/SMSC_R2R_CommonFunction", ReplyAction="*")]
        System.Threading.Tasks.Task SMSC_R2R_CommonFunctionAsync(SMSC_Simulator.R2RReplyService.eventInfo6 SMSC_R2R_CommonFunction_input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Adapter/SMSC_R2R_ControllerService_Reply/SMSC_R2R_Etch_CalcRecipeSettings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SMSC_R2R_Etch_CalcRecipeSettings(SMSC_Simulator.R2RReplyService.eventInfo7 SMSC_R2R_Etch_CalcRecipeSettings_input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Adapter/SMSC_R2R_ControllerService_Reply/SMSC_R2R_Etch_CalcRecipeSettings", ReplyAction="*")]
        System.Threading.Tasks.Task SMSC_R2R_Etch_CalcRecipeSettingsAsync(SMSC_Simulator.R2RReplyService.eventInfo7 SMSC_R2R_Etch_CalcRecipeSettings_input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Adapter/SMSC_R2R_ControllerService_Reply/SMSC_R2R_Etch_Metrology", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SMSC_R2R_Etch_Metrology(SMSC_Simulator.R2RReplyService.eventInfo8 SMSC_R2R_Etch_Metrology_input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Adapter/SMSC_R2R_ControllerService_Reply/SMSC_R2R_Etch_Metrology", ReplyAction="*")]
        System.Threading.Tasks.Task SMSC_R2R_Etch_MetrologyAsync(SMSC_Simulator.R2RReplyService.eventInfo8 SMSC_R2R_Etch_Metrology_input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Adapter/SMSC_R2R_ControllerService_Reply/SMSC_R2R_Etch_UsedSettings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SMSC_R2R_Etch_UsedSettings(SMSC_Simulator.R2RReplyService.eventInfo9 SMSC_R2R_Etch_UsedSettings_input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Adapter/SMSC_R2R_ControllerService_Reply/SMSC_R2R_Etch_UsedSettings", ReplyAction="*")]
        System.Threading.Tasks.Task SMSC_R2R_Etch_UsedSettingsAsync(SMSC_Simulator.R2RReplyService.eventInfo9 SMSC_R2R_Etch_UsedSettings_input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Adapter/SMSC_R2R_ControllerService_Reply/SMSC_R2R_Furnace_CalcRecipeSettin" +
            "gs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SMSC_R2R_Furnace_CalcRecipeSettings(SMSC_Simulator.R2RReplyService.eventInfo10 SMSC_R2R_Furnace_CalcRecipeSettings_input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Adapter/SMSC_R2R_ControllerService_Reply/SMSC_R2R_Furnace_CalcRecipeSettin" +
            "gs", ReplyAction="*")]
        System.Threading.Tasks.Task SMSC_R2R_Furnace_CalcRecipeSettingsAsync(SMSC_Simulator.R2RReplyService.eventInfo10 SMSC_R2R_Furnace_CalcRecipeSettings_input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Adapter/SMSC_R2R_ControllerService_Reply/SMSC_R2R_Furnace_Metrology", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SMSC_R2R_Furnace_Metrology(SMSC_Simulator.R2RReplyService.eventInfo11 SMSC_R2R_Furnace_Metrology_input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Adapter/SMSC_R2R_ControllerService_Reply/SMSC_R2R_Furnace_Metrology", ReplyAction="*")]
        System.Threading.Tasks.Task SMSC_R2R_Furnace_MetrologyAsync(SMSC_Simulator.R2RReplyService.eventInfo11 SMSC_R2R_Furnace_Metrology_input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Adapter/SMSC_R2R_ControllerService_Reply/SMSC_R2R_Furnace_UsedSettings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SMSC_R2R_Furnace_UsedSettings(SMSC_Simulator.R2RReplyService.eventInfo12 SMSC_R2R_Furnace_UsedSettings_input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Adapter/SMSC_R2R_ControllerService_Reply/SMSC_R2R_Furnace_UsedSettings", ReplyAction="*")]
        System.Threading.Tasks.Task SMSC_R2R_Furnace_UsedSettingsAsync(SMSC_Simulator.R2RReplyService.eventInfo12 SMSC_R2R_Furnace_UsedSettings_input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Adapter/SMSC_R2R_ControllerService_Reply/SMSC_R2R_Litho_CalcRecipeSettings" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SMSC_R2R_Litho_CalcRecipeSettings(SMSC_Simulator.R2RReplyService.eventInfo13 SMSC_R2R_Litho_CalcRecipeSettings_input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Adapter/SMSC_R2R_ControllerService_Reply/SMSC_R2R_Litho_CalcRecipeSettings" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task SMSC_R2R_Litho_CalcRecipeSettingsAsync(SMSC_Simulator.R2RReplyService.eventInfo13 SMSC_R2R_Litho_CalcRecipeSettings_input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Adapter/SMSC_R2R_ControllerService_Reply/SMSC_R2R_Litho_Metrology", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SMSC_R2R_Litho_Metrology(SMSC_Simulator.R2RReplyService.eventInfo14 SMSC_R2R_Litho_Metrology_input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Adapter/SMSC_R2R_ControllerService_Reply/SMSC_R2R_Litho_Metrology", ReplyAction="*")]
        System.Threading.Tasks.Task SMSC_R2R_Litho_MetrologyAsync(SMSC_Simulator.R2RReplyService.eventInfo14 SMSC_R2R_Litho_Metrology_input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Adapter/SMSC_R2R_ControllerService_Reply/SMSC_R2R_Litho_UsedSettings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SMSC_R2R_Litho_UsedSettings(SMSC_Simulator.R2RReplyService.eventInfo15 SMSC_R2R_Litho_UsedSettings_input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Adapter/SMSC_R2R_ControllerService_Reply/SMSC_R2R_Litho_UsedSettings", ReplyAction="*")]
        System.Threading.Tasks.Task SMSC_R2R_Litho_UsedSettingsAsync(SMSC_Simulator.R2RReplyService.eventInfo15 SMSC_R2R_Litho_UsedSettings_input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Adapter/SMSC_R2R_ControllerService_Reply/_Ping", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string _Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Adapter/SMSC_R2R_ControllerService_Reply/_Ping", ReplyAction="*")]
        System.Threading.Tasks.Task<string> _PingAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="EES.Core.WebServices.Adapter.SMSC_R2R_CMP_CalcRecipeSettings")]
    public partial class eventInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        private string errDescField;
        
        private string txIdField;
        
        private string xmlStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
                this.RaisePropertyChanged("ErrDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TxId {
            get {
                return this.txIdField;
            }
            set {
                this.txIdField = value;
                this.RaisePropertyChanged("TxId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string XmlString {
            get {
                return this.xmlStringField;
            }
            set {
                this.xmlStringField = value;
                this.RaisePropertyChanged("XmlString");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="eventInfo", Namespace="EES.Core.WebServices.Adapter.SMSC_R2R_Litho_UsedSettings")]
    public partial class eventInfo15 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        private string errDescField;
        
        private string txIdField;
        
        private string xmlStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
                this.RaisePropertyChanged("ErrDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TxId {
            get {
                return this.txIdField;
            }
            set {
                this.txIdField = value;
                this.RaisePropertyChanged("TxId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string XmlString {
            get {
                return this.xmlStringField;
            }
            set {
                this.xmlStringField = value;
                this.RaisePropertyChanged("XmlString");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="eventInfo", Namespace="EES.Core.WebServices.Adapter.SMSC_R2R_Litho_Metrology")]
    public partial class eventInfo14 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        private string errDescField;
        
        private string txIdField;
        
        private string xmlStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
                this.RaisePropertyChanged("ErrDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TxId {
            get {
                return this.txIdField;
            }
            set {
                this.txIdField = value;
                this.RaisePropertyChanged("TxId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string XmlString {
            get {
                return this.xmlStringField;
            }
            set {
                this.xmlStringField = value;
                this.RaisePropertyChanged("XmlString");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="eventInfo", Namespace="EES.Core.WebServices.Adapter.SMSC_R2R_Litho_CalcRecipeSettings")]
    public partial class eventInfo13 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        private string errDescField;
        
        private string txIdField;
        
        private string xmlStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
                this.RaisePropertyChanged("ErrDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TxId {
            get {
                return this.txIdField;
            }
            set {
                this.txIdField = value;
                this.RaisePropertyChanged("TxId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string XmlString {
            get {
                return this.xmlStringField;
            }
            set {
                this.xmlStringField = value;
                this.RaisePropertyChanged("XmlString");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="eventInfo", Namespace="EES.Core.WebServices.Adapter.SMSC_R2R_Furnace_UsedSettings")]
    public partial class eventInfo12 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        private string errDescField;
        
        private string txIdField;
        
        private string xmlStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
                this.RaisePropertyChanged("ErrDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TxId {
            get {
                return this.txIdField;
            }
            set {
                this.txIdField = value;
                this.RaisePropertyChanged("TxId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string XmlString {
            get {
                return this.xmlStringField;
            }
            set {
                this.xmlStringField = value;
                this.RaisePropertyChanged("XmlString");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="eventInfo", Namespace="EES.Core.WebServices.Adapter.SMSC_R2R_Furnace_Metrology")]
    public partial class eventInfo11 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        private string errDescField;
        
        private string txIdField;
        
        private string xmlStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
                this.RaisePropertyChanged("ErrDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TxId {
            get {
                return this.txIdField;
            }
            set {
                this.txIdField = value;
                this.RaisePropertyChanged("TxId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string XmlString {
            get {
                return this.xmlStringField;
            }
            set {
                this.xmlStringField = value;
                this.RaisePropertyChanged("XmlString");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="eventInfo", Namespace="EES.Core.WebServices.Adapter.SMSC_R2R_Furnace_CalcRecipeSettings")]
    public partial class eventInfo10 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        private string errDescField;
        
        private string txIdField;
        
        private string xmlStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
                this.RaisePropertyChanged("ErrDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TxId {
            get {
                return this.txIdField;
            }
            set {
                this.txIdField = value;
                this.RaisePropertyChanged("TxId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string XmlString {
            get {
                return this.xmlStringField;
            }
            set {
                this.xmlStringField = value;
                this.RaisePropertyChanged("XmlString");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="eventInfo", Namespace="EES.Core.WebServices.Adapter.SMSC_R2R_Etch_UsedSettings")]
    public partial class eventInfo9 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        private string errDescField;
        
        private string txIdField;
        
        private string xmlStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
                this.RaisePropertyChanged("ErrDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TxId {
            get {
                return this.txIdField;
            }
            set {
                this.txIdField = value;
                this.RaisePropertyChanged("TxId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string XmlString {
            get {
                return this.xmlStringField;
            }
            set {
                this.xmlStringField = value;
                this.RaisePropertyChanged("XmlString");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="eventInfo", Namespace="EES.Core.WebServices.Adapter.SMSC_R2R_Etch_Metrology")]
    public partial class eventInfo8 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        private string errDescField;
        
        private string txIdField;
        
        private string xmlStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
                this.RaisePropertyChanged("ErrDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TxId {
            get {
                return this.txIdField;
            }
            set {
                this.txIdField = value;
                this.RaisePropertyChanged("TxId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string XmlString {
            get {
                return this.xmlStringField;
            }
            set {
                this.xmlStringField = value;
                this.RaisePropertyChanged("XmlString");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="eventInfo", Namespace="EES.Core.WebServices.Adapter.SMSC_R2R_Etch_CalcRecipeSettings")]
    public partial class eventInfo7 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        private string errDescField;
        
        private string txIdField;
        
        private string xmlStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
                this.RaisePropertyChanged("ErrDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TxId {
            get {
                return this.txIdField;
            }
            set {
                this.txIdField = value;
                this.RaisePropertyChanged("TxId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string XmlString {
            get {
                return this.xmlStringField;
            }
            set {
                this.xmlStringField = value;
                this.RaisePropertyChanged("XmlString");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="eventInfo", Namespace="EES.Core.WebServices.Adapter.SMSC_R2R_CommonFunction")]
    public partial class eventInfo6 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        private string errDescField;
        
        private string txIdField;
        
        private string xmlStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
                this.RaisePropertyChanged("ErrDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TxId {
            get {
                return this.txIdField;
            }
            set {
                this.txIdField = value;
                this.RaisePropertyChanged("TxId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string XmlString {
            get {
                return this.xmlStringField;
            }
            set {
                this.xmlStringField = value;
                this.RaisePropertyChanged("XmlString");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="eventInfo", Namespace="EES.Core.WebServices.Adapter.SMSC_R2R_CVD_UsedSettings")]
    public partial class eventInfo5 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        private string errDescField;
        
        private string txIdField;
        
        private string xmlStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
                this.RaisePropertyChanged("ErrDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TxId {
            get {
                return this.txIdField;
            }
            set {
                this.txIdField = value;
                this.RaisePropertyChanged("TxId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string XmlString {
            get {
                return this.xmlStringField;
            }
            set {
                this.xmlStringField = value;
                this.RaisePropertyChanged("XmlString");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="eventInfo", Namespace="EES.Core.WebServices.Adapter.SMSC_R2R_CVD_Metrology")]
    public partial class eventInfo4 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        private string errDescField;
        
        private string txIdField;
        
        private string xmlStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
                this.RaisePropertyChanged("ErrDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TxId {
            get {
                return this.txIdField;
            }
            set {
                this.txIdField = value;
                this.RaisePropertyChanged("TxId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string XmlString {
            get {
                return this.xmlStringField;
            }
            set {
                this.xmlStringField = value;
                this.RaisePropertyChanged("XmlString");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="eventInfo", Namespace="EES.Core.WebServices.Adapter.SMSC_R2R_CVD_CalcRecipeSettings")]
    public partial class eventInfo3 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        private string errDescField;
        
        private string txIdField;
        
        private string xmlStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
                this.RaisePropertyChanged("ErrDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TxId {
            get {
                return this.txIdField;
            }
            set {
                this.txIdField = value;
                this.RaisePropertyChanged("TxId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string XmlString {
            get {
                return this.xmlStringField;
            }
            set {
                this.xmlStringField = value;
                this.RaisePropertyChanged("XmlString");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="eventInfo", Namespace="EES.Core.WebServices.Adapter.SMSC_R2R_CMP_UsedSettings")]
    public partial class eventInfo2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        private string errDescField;
        
        private string txIdField;
        
        private string xmlStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
                this.RaisePropertyChanged("ErrDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TxId {
            get {
                return this.txIdField;
            }
            set {
                this.txIdField = value;
                this.RaisePropertyChanged("TxId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string XmlString {
            get {
                return this.xmlStringField;
            }
            set {
                this.xmlStringField = value;
                this.RaisePropertyChanged("XmlString");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="eventInfo", Namespace="EES.Core.WebServices.Adapter.SMSC_R2R_CMP_Metrology")]
    public partial class eventInfo1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        private string errDescField;
        
        private string txIdField;
        
        private string xmlStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
                this.RaisePropertyChanged("ErrDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TxId {
            get {
                return this.txIdField;
            }
            set {
                this.txIdField = value;
                this.RaisePropertyChanged("TxId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string XmlString {
            get {
                return this.xmlStringField;
            }
            set {
                this.xmlStringField = value;
                this.RaisePropertyChanged("XmlString");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SMSC_R2R_ControllerService_ReplySoapChannel : SMSC_Simulator.R2RReplyService.SMSC_R2R_ControllerService_ReplySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMSC_R2R_ControllerService_ReplySoapClient : System.ServiceModel.ClientBase<SMSC_Simulator.R2RReplyService.SMSC_R2R_ControllerService_ReplySoap>, SMSC_Simulator.R2RReplyService.SMSC_R2R_ControllerService_ReplySoap {
        
        public SMSC_R2R_ControllerService_ReplySoapClient() {
        }
        
        public SMSC_R2R_ControllerService_ReplySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMSC_R2R_ControllerService_ReplySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSC_R2R_ControllerService_ReplySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSC_R2R_ControllerService_ReplySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SMSC_R2R_CMP_CalcRecipeSettings(SMSC_Simulator.R2RReplyService.eventInfo SMSC_R2R_CMP_CalcRecipeSettings_input) {
            base.Channel.SMSC_R2R_CMP_CalcRecipeSettings(SMSC_R2R_CMP_CalcRecipeSettings_input);
        }
        
        public System.Threading.Tasks.Task SMSC_R2R_CMP_CalcRecipeSettingsAsync(SMSC_Simulator.R2RReplyService.eventInfo SMSC_R2R_CMP_CalcRecipeSettings_input) {
            return base.Channel.SMSC_R2R_CMP_CalcRecipeSettingsAsync(SMSC_R2R_CMP_CalcRecipeSettings_input);
        }
        
        public void SMSC_R2R_CMP_Metrology(SMSC_Simulator.R2RReplyService.eventInfo1 SMSC_R2R_CMP_Metrology_input) {
            base.Channel.SMSC_R2R_CMP_Metrology(SMSC_R2R_CMP_Metrology_input);
        }
        
        public System.Threading.Tasks.Task SMSC_R2R_CMP_MetrologyAsync(SMSC_Simulator.R2RReplyService.eventInfo1 SMSC_R2R_CMP_Metrology_input) {
            return base.Channel.SMSC_R2R_CMP_MetrologyAsync(SMSC_R2R_CMP_Metrology_input);
        }
        
        public void SMSC_R2R_CMP_UsedSettings(SMSC_Simulator.R2RReplyService.eventInfo2 SMSC_R2R_CMP_UsedSettings_input) {
            base.Channel.SMSC_R2R_CMP_UsedSettings(SMSC_R2R_CMP_UsedSettings_input);
        }
        
        public System.Threading.Tasks.Task SMSC_R2R_CMP_UsedSettingsAsync(SMSC_Simulator.R2RReplyService.eventInfo2 SMSC_R2R_CMP_UsedSettings_input) {
            return base.Channel.SMSC_R2R_CMP_UsedSettingsAsync(SMSC_R2R_CMP_UsedSettings_input);
        }
        
        public void SMSC_R2R_CVD_CalcRecipeSettings(SMSC_Simulator.R2RReplyService.eventInfo3 SMSC_R2R_CVD_CalcRecipeSettings_input) {
            base.Channel.SMSC_R2R_CVD_CalcRecipeSettings(SMSC_R2R_CVD_CalcRecipeSettings_input);
        }
        
        public System.Threading.Tasks.Task SMSC_R2R_CVD_CalcRecipeSettingsAsync(SMSC_Simulator.R2RReplyService.eventInfo3 SMSC_R2R_CVD_CalcRecipeSettings_input) {
            return base.Channel.SMSC_R2R_CVD_CalcRecipeSettingsAsync(SMSC_R2R_CVD_CalcRecipeSettings_input);
        }
        
        public void SMSC_R2R_CVD_Metrology(SMSC_Simulator.R2RReplyService.eventInfo4 SMSC_R2R_CVD_Metrology_input) {
            base.Channel.SMSC_R2R_CVD_Metrology(SMSC_R2R_CVD_Metrology_input);
        }
        
        public System.Threading.Tasks.Task SMSC_R2R_CVD_MetrologyAsync(SMSC_Simulator.R2RReplyService.eventInfo4 SMSC_R2R_CVD_Metrology_input) {
            return base.Channel.SMSC_R2R_CVD_MetrologyAsync(SMSC_R2R_CVD_Metrology_input);
        }
        
        public void SMSC_R2R_CVD_UsedSettings(SMSC_Simulator.R2RReplyService.eventInfo5 SMSC_R2R_CVD_UsedSettings_input) {
            base.Channel.SMSC_R2R_CVD_UsedSettings(SMSC_R2R_CVD_UsedSettings_input);
        }
        
        public System.Threading.Tasks.Task SMSC_R2R_CVD_UsedSettingsAsync(SMSC_Simulator.R2RReplyService.eventInfo5 SMSC_R2R_CVD_UsedSettings_input) {
            return base.Channel.SMSC_R2R_CVD_UsedSettingsAsync(SMSC_R2R_CVD_UsedSettings_input);
        }
        
        public void SMSC_R2R_CommonFunction(SMSC_Simulator.R2RReplyService.eventInfo6 SMSC_R2R_CommonFunction_input) {
            base.Channel.SMSC_R2R_CommonFunction(SMSC_R2R_CommonFunction_input);
        }
        
        public System.Threading.Tasks.Task SMSC_R2R_CommonFunctionAsync(SMSC_Simulator.R2RReplyService.eventInfo6 SMSC_R2R_CommonFunction_input) {
            return base.Channel.SMSC_R2R_CommonFunctionAsync(SMSC_R2R_CommonFunction_input);
        }
        
        public void SMSC_R2R_Etch_CalcRecipeSettings(SMSC_Simulator.R2RReplyService.eventInfo7 SMSC_R2R_Etch_CalcRecipeSettings_input) {
            base.Channel.SMSC_R2R_Etch_CalcRecipeSettings(SMSC_R2R_Etch_CalcRecipeSettings_input);
        }
        
        public System.Threading.Tasks.Task SMSC_R2R_Etch_CalcRecipeSettingsAsync(SMSC_Simulator.R2RReplyService.eventInfo7 SMSC_R2R_Etch_CalcRecipeSettings_input) {
            return base.Channel.SMSC_R2R_Etch_CalcRecipeSettingsAsync(SMSC_R2R_Etch_CalcRecipeSettings_input);
        }
        
        public void SMSC_R2R_Etch_Metrology(SMSC_Simulator.R2RReplyService.eventInfo8 SMSC_R2R_Etch_Metrology_input) {
            base.Channel.SMSC_R2R_Etch_Metrology(SMSC_R2R_Etch_Metrology_input);
        }
        
        public System.Threading.Tasks.Task SMSC_R2R_Etch_MetrologyAsync(SMSC_Simulator.R2RReplyService.eventInfo8 SMSC_R2R_Etch_Metrology_input) {
            return base.Channel.SMSC_R2R_Etch_MetrologyAsync(SMSC_R2R_Etch_Metrology_input);
        }
        
        public void SMSC_R2R_Etch_UsedSettings(SMSC_Simulator.R2RReplyService.eventInfo9 SMSC_R2R_Etch_UsedSettings_input) {
            base.Channel.SMSC_R2R_Etch_UsedSettings(SMSC_R2R_Etch_UsedSettings_input);
        }
        
        public System.Threading.Tasks.Task SMSC_R2R_Etch_UsedSettingsAsync(SMSC_Simulator.R2RReplyService.eventInfo9 SMSC_R2R_Etch_UsedSettings_input) {
            return base.Channel.SMSC_R2R_Etch_UsedSettingsAsync(SMSC_R2R_Etch_UsedSettings_input);
        }
        
        public void SMSC_R2R_Furnace_CalcRecipeSettings(SMSC_Simulator.R2RReplyService.eventInfo10 SMSC_R2R_Furnace_CalcRecipeSettings_input) {
            base.Channel.SMSC_R2R_Furnace_CalcRecipeSettings(SMSC_R2R_Furnace_CalcRecipeSettings_input);
        }
        
        public System.Threading.Tasks.Task SMSC_R2R_Furnace_CalcRecipeSettingsAsync(SMSC_Simulator.R2RReplyService.eventInfo10 SMSC_R2R_Furnace_CalcRecipeSettings_input) {
            return base.Channel.SMSC_R2R_Furnace_CalcRecipeSettingsAsync(SMSC_R2R_Furnace_CalcRecipeSettings_input);
        }
        
        public void SMSC_R2R_Furnace_Metrology(SMSC_Simulator.R2RReplyService.eventInfo11 SMSC_R2R_Furnace_Metrology_input) {
            base.Channel.SMSC_R2R_Furnace_Metrology(SMSC_R2R_Furnace_Metrology_input);
        }
        
        public System.Threading.Tasks.Task SMSC_R2R_Furnace_MetrologyAsync(SMSC_Simulator.R2RReplyService.eventInfo11 SMSC_R2R_Furnace_Metrology_input) {
            return base.Channel.SMSC_R2R_Furnace_MetrologyAsync(SMSC_R2R_Furnace_Metrology_input);
        }
        
        public void SMSC_R2R_Furnace_UsedSettings(SMSC_Simulator.R2RReplyService.eventInfo12 SMSC_R2R_Furnace_UsedSettings_input) {
            base.Channel.SMSC_R2R_Furnace_UsedSettings(SMSC_R2R_Furnace_UsedSettings_input);
        }
        
        public System.Threading.Tasks.Task SMSC_R2R_Furnace_UsedSettingsAsync(SMSC_Simulator.R2RReplyService.eventInfo12 SMSC_R2R_Furnace_UsedSettings_input) {
            return base.Channel.SMSC_R2R_Furnace_UsedSettingsAsync(SMSC_R2R_Furnace_UsedSettings_input);
        }
        
        public void SMSC_R2R_Litho_CalcRecipeSettings(SMSC_Simulator.R2RReplyService.eventInfo13 SMSC_R2R_Litho_CalcRecipeSettings_input) {
            base.Channel.SMSC_R2R_Litho_CalcRecipeSettings(SMSC_R2R_Litho_CalcRecipeSettings_input);
        }
        
        public System.Threading.Tasks.Task SMSC_R2R_Litho_CalcRecipeSettingsAsync(SMSC_Simulator.R2RReplyService.eventInfo13 SMSC_R2R_Litho_CalcRecipeSettings_input) {
            return base.Channel.SMSC_R2R_Litho_CalcRecipeSettingsAsync(SMSC_R2R_Litho_CalcRecipeSettings_input);
        }
        
        public void SMSC_R2R_Litho_Metrology(SMSC_Simulator.R2RReplyService.eventInfo14 SMSC_R2R_Litho_Metrology_input) {
            base.Channel.SMSC_R2R_Litho_Metrology(SMSC_R2R_Litho_Metrology_input);
        }
        
        public System.Threading.Tasks.Task SMSC_R2R_Litho_MetrologyAsync(SMSC_Simulator.R2RReplyService.eventInfo14 SMSC_R2R_Litho_Metrology_input) {
            return base.Channel.SMSC_R2R_Litho_MetrologyAsync(SMSC_R2R_Litho_Metrology_input);
        }
        
        public void SMSC_R2R_Litho_UsedSettings(SMSC_Simulator.R2RReplyService.eventInfo15 SMSC_R2R_Litho_UsedSettings_input) {
            base.Channel.SMSC_R2R_Litho_UsedSettings(SMSC_R2R_Litho_UsedSettings_input);
        }
        
        public System.Threading.Tasks.Task SMSC_R2R_Litho_UsedSettingsAsync(SMSC_Simulator.R2RReplyService.eventInfo15 SMSC_R2R_Litho_UsedSettings_input) {
            return base.Channel.SMSC_R2R_Litho_UsedSettingsAsync(SMSC_R2R_Litho_UsedSettings_input);
        }
        
        public string _Ping() {
            return base.Channel._Ping();
        }
        
        public System.Threading.Tasks.Task<string> _PingAsync() {
            return base.Channel._PingAsync();
        }
    }
}
